### ISSUE TITLE
Multiple instances of the program

### ISSUE THREAD

**Issue by GeoB99** [arnavbhatt288/ros-ram-disk-creator#2]
At this moment you can execute the program more than once resulting in multiple instances which is an incorrect behaviour as the program must have only one instance (launched only once).

I can give you a workaround on how to fix it. Mutant objects (mutual exclusion or mutex in other words) is the classic technique to avoid multiple instances of a program. This works by creating a mutant object by using `CreateMutexW()` function from Synchronization API (`synchapi.h` as header) on the first ever instance (when `wWinMain` entry point gets initialized). When the user attempts to launch the program again, it'll exit gracefully as the named mutant object has already been created and thus it cannot be created again of the same name (as the previous instance owns it).

## How to do that
**1.** First assign the variable (keep in mind the function expects a `HANDLE` data type which is a resource memory in `PVOID`) to `CreateMutexW()`. You can set the security attributes structure to NULL as we do not want the handle to be inherited by child processes, it's up to you.
**2.** The second parameter is `bInitialOwner` which you allow or not the main program to obtain ownership of the said named mutex. You can set it to **FALSE**. Finally, the third parameter is what you define the name of the object.
**3.** With your variable, check if the call has returned your handle of the mutant object. At this point you have to make sure that ONLY ONE named object can exist and no other more. To do so you must shall check against `ERROR_ALREADY_EXISTS` as with CreateMutexW() you can use `GetLastError()` to gather extended information. If `ERROR_ALREADY_EXISTS` condition has been hit which means the named object has been already created previously by the entry instance of the program, then free the handle with `CloseHandle()` and exit gracefully.

Make sure that at the end of your program when you attempt to close it, free the handle object from the memory with the same call - `CloseHandle()`. This may require a little code change on `wWinMain` so if you have doubts, please ask me.

**Comment by abt2804** [comment]
Added this function in new function. Thank you for suggesting me.
Have a nice day!
